# Generated by Django 2.2.7 on 2021-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210411_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
