# Generated by Django 2.2.7 on 2021-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
