# Generated by Django 2.2.7 on 2021-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
