# Generated by Django 2.2.7 on 2021-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_responses',
            field=models.IntegerField(default=0),
        ),
    ]
