# Generated by Django 2.2.7 on 2021-04-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_question_total_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
