# Generated by Django 2.2.7 on 2021-04-17 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_userprofile_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reporters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
