# Generated by Django 2.2.7 on 2021-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210421_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
