# Generated by Django 3.2 on 2021-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_response_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='best_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
