# Generated by Django 3.2 on 2021-07-02 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210702_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_online_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 20, 52, 40, 211741, tzinfo=utc)),
        ),
    ]
