# Generated by Django 3.2 on 2021-07-02 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_userstatus_last_online_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_online_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 20, 53, 13, 894358, tzinfo=utc)),
        ),
    ]
