# Generated by Django 3.2 on 2021-07-02 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_userstatus_last_online_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_online_confirmation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
