# Generated by Django 3.2 on 2021-07-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_userstatus_last_online_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='last_online_confirmation',
            new_name='last_seen',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='online',
        ),
    ]
