# Generated by Django 3.2 on 2021-07-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210702_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
